export * from './navbar/navbar.component';
export * from './footer/footer.component';
export * from './welcome/welcome.component';
export * from './maps/maps.component';
export * from './contact/contact.component';
export * from './schedules/schedules.component';
export * from './gallery/gallery.component';
export * from './welcome/welcome.component';
export * from './sobre-nosotros/sobre-nosotros.component';
